services:
  - type: web
    name: vybe-telegram-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/app.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: VYBE_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: VYBE_API_BASE_URL
        value: https://api.vybenetwork.xyz
    autoDeploy: true