name: Telegram bot CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Just build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker Image
      run: docker compose build

    - name: Run test
      run: npm test

    
  deploy:
    needs: Just build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Production(Render)
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
        ssh $DEPLOY_USER@$DEPLOY_HOST << EOF
          cd /path/to/your/project
          git pull origin main
          docker compose down
          docker compose up -d --build
        EOF